const now = Date.now();
const minutesAgo = (m) => new Date(now - m * 60 * 1000).toISOString();

export const patients = [
  {
    id: 1,
    name: "Sarah Johnson",
    age: 67,
    room: "2A-312",
    diagnosis: "Community-acquired pneumonia with hypoxia",
    admissionDate: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    codeStatus: "Full Code",
    allergies: ["Penicillin", "Sulfa"],
    attendingPhysician: "Dr. Patel",
    comments: [
      {
        id: 1001,
        text: "Patient reporting pain level 6/10, requesting pain management review",
        category: "Assessment",
        timestamp: minutesAgo(20),
      },
      {
        id: 1002,
        text: "Daughter visiting at 3pm, wants to discuss discharge plan with attending",
        category: "Recommendation",
        timestamp: minutesAgo(10),
      },
    ],
    contacts: [
      {
        id: 10001,
        name: "Maria Johnson",
        relationship: "Daughter",
        phone: "+1 555-0123",
        email: "maria.johnson@email.com",
        preferredMethod: "email",
      },
      {
        id: 10002,
        name: "Tom Johnson",
        relationship: "Spouse",
        phone: "+1 555-0456",
        email: "",
        preferredMethod: "text",
      },
    ],
    tasks: [
      {
        id: 101,
        description: "MRI brain with contrast",
        department: "Radiology",
        status: "Pending",
        timestamp: minutesAgo(14),
        priority: "Routine",
        deadline: new Date(now + 4 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 102,
        description: "Lantus 10 units subcutaneous",
        department: "Pharmacy",
        status: "Confirmed",
        timestamp: minutesAgo(45),
        priority: "Routine",
        deadline: null,
      },
      {
        id: 103,
        description: "Complete Blood Count with differential",
        department: "Lab",
        status: "Pending",
        timestamp: minutesAgo(8),
        priority: "Stat",
        deadline: new Date(now + 45 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 2,
    name: "Maria Santos",
    age: 45,
    room: "2B-415",
    diagnosis: "Acute cholecystitis, awaiting surgical consult",
    admissionDate: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
    codeStatus: "Full Code",
    allergies: ["Codeine"],
    attendingPhysician: "Dr. Nguyen",
    comments: [],
    contacts: [
      {
        id: 20001,
        name: "Carlos Santos",
        relationship: "Spouse",
        phone: "+1 555-0789",
        email: "carlos.santos@email.com",
        preferredMethod: "both",
      },
    ],
    tasks: [
      {
        id: 201,
        description: "Abdominal Ultrasound",
        department: "Radiology",
        status: "Pending",
        timestamp: minutesAgo(47),
        priority: "Urgent",
        deadline: new Date(now - 30 * 60 * 1000).toISOString(),
      },
      {
        id: 202,
        description: "Lipid Panel",
        department: "Lab",
        status: "Confirmed",
        timestamp: minutesAgo(12),
        priority: "Routine",
        deadline: null,
      },
      {
        id: 9001,
        description: "Abdominal Ultrasound",
        department: "Radiology",
        status: "Pending",
        priority: "Routine",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        deadline: null,
      },
    ],
  },
  {
    id: 3,
    name: "Robert Chen",
    age: 58,
    room: "3A-208",
    diagnosis: "Lumbar radiculopathy with new onset weakness",
    admissionDate: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    codeStatus: "Full Code",
    allergies: [],
    attendingPhysician: "Dr. Okafor",
    comments: [
      {
        id: 3001,
        text: "Patient anxious about MRI, has history of claustrophobia. May need anxiolytic premedication",
        category: "Background",
        timestamp: minutesAgo(30),
      },
    ],
    contacts: [
      {
        id: 30001,
        name: "Lisa Chen",
        relationship: "Spouse",
        phone: "",
        email: "lisa.chen@email.com",
        preferredMethod: "email",
      },
      {
        id: 30002,
        name: "David Chen",
        relationship: "Son",
        phone: "+1 555-0234",
        email: "david.chen@email.com",
        preferredMethod: "both",
      },
    ],
    tasks: [
      {
        id: 301,
        description: "MRI Lower Spine",
        department: "Radiology",
        status: "Pending",
        timestamp: minutesAgo(55),
        priority: "Urgent",
        deadline: new Date(now + 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 302,
        description: "Dispense Ibuprofen 400mg",
        department: "Pharmacy",
        status: "Confirmed",
        timestamp: minutesAgo(15),
        priority: "Urgent",
        deadline: new Date(now + 20 * 60 * 1000).toISOString(),
      },
      {
        id: 303,
        description: "Basic Metabolic Panel",
        department: "Lab",
        status: "Pending",
        timestamp: minutesAgo(38),
        priority: "Routine",
        deadline: new Date(now - 15 * 60 * 1000).toISOString(),
      },
      {
        id: 9002,
        description: "Basic Metabolic Panel",
        department: "Lab",
        status: "Pending",
        priority: "Routine",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        deadline: null,
      },
    ],
  },
  {
    id: 4,
    name: "Robert Martinez",
    age: 81,
    room: "3B-208",
    diagnosis: "Left hip fracture, post-operative day 2",
    admissionDate: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    codeStatus: "DNR/DNI",
    allergies: ["Aspirin", "Latex"],
    attendingPhysician: "Dr. Kim",
    comments: [
      {
        id: 4001,
        text: "Fall risk, bed alarm activated. Patient attempted to get up unassisted twice this shift",
        category: "Assessment",
        timestamp: minutesAgo(25),
      },
      {
        id: 4002,
        text: "Family requesting meeting with social worker regarding post-discharge care options",
        category: "Situation",
        timestamp: minutesAgo(12),
      },
    ],
    contacts: [
      {
        id: 40001,
        name: "Elena Martinez",
        relationship: "Daughter",
        phone: "+1 555-0567",
        email: "",
        preferredMethod: "text",
      },
    ],
    tasks: [
      {
        id: 401,
        description: "Physical Therapy evaluation",
        department: "Physical Therapy",
        status: "Pending",
        timestamp: minutesAgo(18),
        priority: "Routine",
        deadline: new Date(now + 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 5,
    name: "Jennifer Johnson",
    age: 45,
    room: "4A-101",
    diagnosis: "New-onset atrial fibrillation with RVR",
    admissionDate: new Date(now - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    codeStatus: "Full Code",
    allergies: ["Iodine contrast"],
    attendingPhysician: "Dr. Patel",
    comments: [],
    contacts: [],
    tasks: [
      {
        id: 501,
        description: "Basic Metabolic Panel",
        department: "Lab",
        status: "Pending",
        timestamp: minutesAgo(5),
        priority: "Routine",
        deadline: null,
      },
    ],
  },
];
